spring.application.name=MusicUpc
server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d806mnd0lvsc738eb830-a.oregon-postgres.render.com:5432/musicupcbd
spring.datasource.username=josue
spring.datasource.password=GtXpalTN5CCULSAqCpLW7P5eTssbrbTn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MusicUpcSecretKeyMusicUpcSecretKey12345
jwt.expiration=86400000
springdoc.swagger-ui.path=/swagger-ui.html